{%- set name = "bg-mpl-stylesheets" -%}
{%- set version = "0.3.2" -%}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/bg_mpl_stylesheets/bg_mpl_stylesheets-{{ version }}.tar.gz
  sha256: 024057949fa4329733924eb6f903d12883a7bb859c3a6a1e99701bb110b9b706

build:
  preserve_egg_dir: true
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python >=3.10
    - setuptools
    - pip

  run:
    - python >=3.10
    - setuptools
    - matplotlib-base

test:
  imports:
    - bg_mpl_stylesheets

  requires:
    - pytest
    - flake8
    - codecov
    - coverage
    - pytest-env

about:
  home: https://github.com/billingegroup/bg-mpl-stylesheets/
  summary: A package for using Billinge group style files
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  description: |
    bg-mpl-stylesheets is a Python software package that creates a standardized matplotlib figure format. This includes specialized fonts, figure border, color cycle, tick parameters, and more.
  doc_url: http://billingegroup.github.io/bg-mpl-stylesheets/
  dev_url: https://github.com/billingegroup/bg-mpl-stylesheets/

extra:
  recipe-maintainers:
    - sbillinge
    - bobleesj
