{%- set name = "bg-mpl-stylesheets" -%}
{%- set version = "0.5.1" -%}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/bg_mpl_stylesheets/bg_mpl_stylesheets-{{ version }}.tar.gz
  sha256: 152682a7354777a7b2af274dd644ffd9c79ba07485cda2c69298cd3cf80a9c5a

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - {{ python_min }}
    - setuptools
    - setuptools-git-versioning >=2.0
    - pip

  run:
    - python >={{ python_min }}
    - matplotlib-base

test:
  imports:
    - bg_mpl_stylesheets
  requires:
    - python {{ python_min }} 
    - pip
    - pytest
  source_files:
    - tests
  commands:
    - pip check
    - pytest

about:
  home: https://github.com/billingegroup/bg-mpl-stylesheets/
  summary: A package for using Billinge group style files
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  description: |
    bg-mpl-stylesheets is a Python software package that creates a standardized matplotlib figure format. This includes specialized fonts, figure border, color cycle, tick parameters, and more.
  doc_url: http://billingegroup.github.io/bg-mpl-stylesheets/
  dev_url: https://github.com/billingegroup/bg-mpl-stylesheets/

extra:
  recipe-maintainers:
    - bobleesj
    - sbillinge
