{% set group = "Billingegroup" %}
{% set name = "bg-mpl-stylesheets" %}
{% set version = "0.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://github.com/{{ group }}/{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: d319c97649861b55b67313938c6cccc131b0589d74ee2613154ff0b70447859f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - matplotlib-base

test:
  imports:
    - bg_mpl_stylesheet

about:
  home: https://github.com/{{ group }}/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Defines a standardized matplotlib stylesheet for the Billinge Group

extra:
  recipe-maintainers:
    - sbillinge
    - connorjbracy
