{% set group = "Billingegroup" %}
{% set name = "bg-mpl-stylesheets" %}
{% set version = "test" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://github.com/{{ group }}/{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 987d63db7ed37c9fda36be31df614f4e182f85473bc39b8fecfbc44a8ff1034c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - matplotlib-base

test:
  imports:
    - bg_mpl_stylesheet

about:
  home: https://github.com/{{ group }}/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Defines a standardized matplotlib stylesheet for the Billinge Group

extra:
  recipe-maintainers:
    - sbillinge
    - connorjbracy
